# .tfvars files
*.tfvars

# Exclude for testing stuff.
!testing.tfvars

# .tfstate files
*.tfstate
*.tfstate.*

# Go vendor directory
vendor/

# Files generated by terratest
.test-data/

# Local .terraform directory
**/.terraform/*

# IDE config files
**/.idea/*
**/.vscode/*

# MacOS files
.DS_Store

# Ruby downloaded package lock file.
Gemfile.lock

# Local test-kitchen files.
**/.kitchen/*
